services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata2: